
--Create Database, Schema, and Stage
CREATE OR REPLACE DATABASE WATER_POLLUTION_DB;
USE DATABASE WATER_POLLUTION_DB;

CREATE OR REPLACE SCHEMA WATER_DATA;
USE SCHEMA WATER_DATA;

-- Create an internal stage to hold the JSON file
CREATE OR REPLACE STAGE WATER_STAGE;

-- Create table
CREATE OR REPLACE TABLE WATER_POLLUTION_RAW (
    json_data VARIANT
);

-- Load JSON Data into Raw Table
COPY INTO WATER_POLLUTION_RAW
FROM @WATER_STAGE/csvjson.json
FILE_FORMAT = (TYPE = 'JSON');
